from models.network import Network
from models.fcn import FCN
from models.pspnet import PSPNet
from models.segnet import SegNet
from models.unet import UNet
from models.pan import PAN
from models.deeplab_v3 import DeepLabV3
from models.deeplab_v3_plus import DeepLabV3Plus
from models.refinenet import RefineNet
from models.denseaspp import DenseASPP
from models.bisegnet import BiSegNet
